apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hs-verifier
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - verifier-staging.hskernel.dev
      secretName: hs-verifier-staging-tls
  rules:
    - host: verifier-staging.hskernel.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hs-verifier
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transparency-log
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - log-staging.hskernel.dev
      secretName: transparency-log-staging-tls
  rules:
    - host: log-staging.hskernel.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transparency-log-public
                port:
                  number: 443
