apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-verifier
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: verifier
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: RUST_LOG
              value: "debug"
            - name: RUST_BACKTRACE
              value: "1"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hs-verifier
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
